"""baseline schema

Revision ID: e9054a84d196
Revises: 
Create Date: 2026-07-31 23:15:54.539874

"""
from alembic import op
import sqlalchemy as sa


revision = 'e9054a84d196'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dict_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'name', name='uq_dict_category_name')
    )
    op.create_index(op.f('ix_dict_options_category'), 'dict_options', ['category'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('owner_name', sa.String(length=64), nullable=False),
    sa.Column('owner_phone', sa.String(length=32), nullable=False),
    sa.Column('owner_email', sa.String(length=128), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sub_system', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('public_urls', sa.JSON(), nullable=True),
    sa.Column('internal_urls', sa.JSON(), nullable=True),
    sa.Column('ports', sa.JSON(), nullable=True),
    sa.Column('services', sa.String(length=255), nullable=False),
    sa.Column('middleware', sa.String(length=128), nullable=False),
    sa.Column('database_type', sa.String(length=128), nullable=False),
    sa.Column('port_services', sa.JSON(), nullable=True),
    sa.Column('middlewares', sa.JSON(), nullable=True),
    sa.Column('databases', sa.JSON(), nullable=True),
    sa.Column('owners', sa.JSON(), nullable=True),
    sa.Column('sec_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('realname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('group_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('doc_kind', sa.String(length=16), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_name', sa.String(length=255), nullable=False),
    sa.Column('vul_type', sa.Integer(), nullable=False),
    sa.Column('severity_level', sa.Integer(), nullable=False),
    sa.Column('description_html', sa.Text(), nullable=False),
    sa.Column('description_json', sa.JSON(), nullable=True),
    sa.Column('harm_html', sa.Text(), nullable=False),
    sa.Column('harm_json', sa.JSON(), nullable=True),
    sa.Column('solution_html', sa.Text(), nullable=False),
    sa.Column('solution_json', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_vul_type'), 'knowledge_entries', ['vul_type'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_vulnerability_name'), 'knowledge_entries', ['vulnerability_name'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('msg_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('spring_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_no', sa.String(length=128), nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('year', sa.String(length=8), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=False),
    sa.Column('appeal_success', sa.Boolean(), nullable=False),
    sa.Column('score_deduction', sa.Float(), nullable=False),
    sa.Column('doc_no', sa.String(length=128), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spring_actions_report_no'), 'spring_actions', ['report_no'], unique=False)
    op.create_table('testing_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('test_type', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('receive_time', sa.String(length=32), nullable=False),
    sa.Column('first_test_done_time', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('retest_notice_time', sa.String(length=32), nullable=False),
    sa.Column('retest_done_time', sa.String(length=32), nullable=False),
    sa.Column('stat_critical', sa.Integer(), nullable=False),
    sa.Column('stat_high', sa.Integer(), nullable=False),
    sa.Column('stat_medium', sa.Integer(), nullable=False),
    sa.Column('stat_low', sa.Integer(), nullable=False),
    sa.Column('est_mandays', sa.Float(), nullable=False),
    sa.Column('actual_mandays', sa.Float(), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testing_plans_system_name'), 'testing_plans', ['system_name'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('customer', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('test_start', sa.String(length=32), nullable=False),
    sa.Column('test_end', sa.String(length=32), nullable=False),
    sa.Column('target_ip', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('testing_plan_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['testing_plan_id'], ['testing_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testing_plan_retest_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('done_time', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['testing_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testing_plan_retest_rounds_plan_id'), 'testing_plan_retest_rounds', ['plan_id'], unique=False)
    op.create_table('testing_plan_testers',
    sa.Column('testing_plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['testing_plan_id'], ['testing_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('testing_plan_id', 'user_id'),
    sa.UniqueConstraint('testing_plan_id', 'user_id', name='uq_testing_plan_tester')
    )
    op.create_table('vulns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('vul_type', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=False),
    sa.Column('affected_url', sa.String(length=512), nullable=False),
    sa.Column('description_html', sa.Text(), nullable=False),
    sa.Column('description_json', sa.JSON(), nullable=True),
    sa.Column('reproduce_html', sa.Text(), nullable=False),
    sa.Column('reproduce_json', sa.JSON(), nullable=True),
    sa.Column('solution_html', sa.Text(), nullable=False),
    sa.Column('solution_json', sa.JSON(), nullable=True),
    sa.Column('retest_html', sa.Text(), nullable=False),
    sa.Column('retest_json', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('left_risk_score', sa.Integer(), nullable=False),
    sa.Column('asset_level', sa.Integer(), nullable=False),
    sa.Column('is_retest', sa.Boolean(), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('delay_reason', sa.Text(), nullable=False),
    sa.Column('testing_plan_id', sa.Integer(), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=False),
    sa.Column('audit_time', sa.DateTime(), nullable=True),
    sa.Column('notice_time', sa.DateTime(), nullable=True),
    sa.Column('fix_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['testing_plan_id'], ['testing_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulns_status'), 'vulns', ['status'], unique=False)
    op.create_index(op.f('ix_vulns_testing_plan_id'), 'vulns', ['testing_plan_id'], unique=False)
    op.create_index(op.f('ix_vulns_title'), 'vulns', ['title'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('fmt', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_report_id'), 'export_jobs', ['report_id'], unique=False)
    op.create_table('import_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('vul_type', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('affected_url', sa.String(length=512), nullable=False),
    sa.Column('description_html', sa.Text(), nullable=False),
    sa.Column('reproduce_html', sa.Text(), nullable=False),
    sa.Column('solution_html', sa.Text(), nullable=False),
    sa.Column('retest_html', sa.Text(), nullable=False),
    sa.Column('fixed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=False),
    sa.Column('vul_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['vul_id'], ['vulns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_records_batch_id'), 'import_records', ['batch_id'], unique=False)
    op.create_table('remote_testings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('test_time', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('appeal_success', sa.Boolean(), nullable=False),
    sa.Column('appeal_report_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appeal_report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remote_testings_title'), 'remote_testings', ['title'], unique=False)
    op.create_table('report_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('vul_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['vul_id'], ['vulns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_sections_report_id'), 'report_sections', ['report_id'], unique=False)
    op.create_table('spring_action_vulns',
    sa.Column('spring_action_id', sa.Integer(), nullable=False),
    sa.Column('vul_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spring_action_id'], ['spring_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vul_id'], ['vulns.id'], ),
    sa.PrimaryKeyConstraint('spring_action_id', 'vul_id'),
    sa.UniqueConstraint('spring_action_id', 'vul_id', name='uq_spring_action_vul')
    )
    op.create_table('vul_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vul_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vul_id'], ['vulns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vul_logs_vul_id'), 'vul_logs', ['vul_id'], unique=False)
    op.create_table('vul_retest_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vul_id', sa.Integer(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vul_id'], ['vulns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vul_retest_records_vul_id'), 'vul_retest_records', ['vul_id'], unique=False)
    op.create_table('vuln_assets',
    sa.Column('vul_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['vul_id'], ['vulns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vul_id', 'asset_id'),
    sa.UniqueConstraint('vul_id', 'asset_id', name='uq_vuln_asset')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vuln_assets')
    op.drop_index(op.f('ix_vul_retest_records_vul_id'), table_name='vul_retest_records')
    op.drop_table('vul_retest_records')
    op.drop_index(op.f('ix_vul_logs_vul_id'), table_name='vul_logs')
    op.drop_table('vul_logs')
    op.drop_table('spring_action_vulns')
    op.drop_index(op.f('ix_report_sections_report_id'), table_name='report_sections')
    op.drop_table('report_sections')
    op.drop_index(op.f('ix_remote_testings_title'), table_name='remote_testings')
    op.drop_table('remote_testings')
    op.drop_index(op.f('ix_import_records_batch_id'), table_name='import_records')
    op.drop_table('import_records')
    op.drop_index(op.f('ix_export_jobs_report_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_vulns_title'), table_name='vulns')
    op.drop_index(op.f('ix_vulns_testing_plan_id'), table_name='vulns')
    op.drop_index(op.f('ix_vulns_status'), table_name='vulns')
    op.drop_table('vulns')
    op.drop_table('testing_plan_testers')
    op.drop_index(op.f('ix_testing_plan_retest_rounds_plan_id'), table_name='testing_plan_retest_rounds')
    op.drop_table('testing_plan_retest_rounds')
    op.drop_table('reports')
    op.drop_index(op.f('ix_testing_plans_system_name'), table_name='testing_plans')
    op.drop_table('testing_plans')
    op.drop_index(op.f('ix_spring_actions_report_no'), table_name='spring_actions')
    op.drop_table('spring_actions')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_knowledge_entries_vulnerability_name'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_vul_type'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_table('import_batches')
    op.drop_table('group_users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('roles')
    op.drop_table('groups')
    op.drop_index(op.f('ix_dict_options_category'), table_name='dict_options')
    op.drop_table('dict_options')
    # ### end Alembic commands ###
